version: '3.9'

services:

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: app-api
    container_name: ed-app
    env_file: .env
    ports:
      - 3000:3000
    networks:
      - app_network
    environment:
      - APP_DB_URL=postgres://username:password@database/app?sslmode=disable
    volumes:
      - ./application.log/:/app/application.log:rw
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:14-alpine
    container_name: ed-db
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - app_network
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app_network:
    name: app_network 
    driver: bridge

volumes:
  app_volume:
