/*
 * tbd
 *
 * This is the REST API specification
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateUserRequest struct {
	FirstName string `json:"firstName"`
	LastName string `json:"lastName"`
	Birth string `json:"birth"`
	Email string `json:"email"`
	Password string `json:"password"`
}
