/*
 * tbd
 *
 * This is the REST API specification
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateTokenRequest struct {
	Email string `json:"email"`
	Password string `json:"password"`
}
