/*
 * tbd
 *
 * This is the REST API specification
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Token struct {
	Token string `json:"token"`
	Expiry string `json:"expiry"`
}
